name: lib_common
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter
  get_it: 7.2.0
  flutter_secure_storage: 5.0.2
  shared_preferences: 2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 1.11.0